<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260505023250 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE tags_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE favorites_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE loyalty_points_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE waitlist_entries_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reviews_id_seq CASCADE');
        $this->addSql('ALTER TABLE voyage_tags DROP CONSTRAINT fk_ff2e5ca8bad26311');
        $this->addSql('ALTER TABLE voyage_tags DROP CONSTRAINT fk_ff2e5ca868c9e5af');
        $this->addSql('DROP TABLE favorites');
        $this->addSql('DROP TABLE loyalty_points');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE tags');
        $this->addSql('DROP TABLE voyage_tags');
        $this->addSql('DROP TABLE waitlist_entries');
        $this->addSql('ALTER TABLE offers DROP flash_sale_ends_at');
        $this->addSql('ALTER TABLE offers DROP flash_sale_discount');
        $this->addSql('ALTER TABLE offers ALTER start_date TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE offers ALTER end_date TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE reclamations DROP response_deadline');
        $this->addSql('ALTER TABLE refund_requests DROP reservation_id');
        $this->addSql('ALTER TABLE refund_requests DROP approved_amount');
        $this->addSql('ALTER TABLE reservations DROP payment_reference');
        $this->addSql('DROP INDEX uniq_30f7f9989d9b62');
        $this->addSql('ALTER TABLE voyages DROP slug');
        $this->addSql('ALTER TABLE voyages ALTER start_date TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE voyages ALTER end_date TYPE TIMESTAMP(0) WITH TIME ZONE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE tags_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE favorites_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE loyalty_points_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE waitlist_entries_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reviews_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE favorites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, voyage_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_voyage ON favorites (user_id, voyage_id)');
        $this->addSql('CREATE TABLE loyalty_points (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, points_balance INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_e0c7d07da76ed395 ON loyalty_points (user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('CREATE TABLE reviews (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, voyage_id INT NOT NULL, rating SMALLINT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_review_user_voyage ON reviews (user_id, voyage_id)');
        $this->addSql('CREATE TABLE tags (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(30) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE voyage_tags (voyage_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (voyage_id, tag_id))');
        $this->addSql('CREATE INDEX idx_ff2e5ca868c9e5af ON voyage_tags (voyage_id)');
        $this->addSql('CREATE INDEX idx_ff2e5ca8bad26311 ON voyage_tags (tag_id)');
        $this->addSql('CREATE TABLE waitlist_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, voyage_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notified BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_voyage_waitlist ON waitlist_entries (user_id, voyage_id)');
        $this->addSql('ALTER TABLE voyage_tags ADD CONSTRAINT fk_ff2e5ca8bad26311 FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voyage_tags ADD CONSTRAINT fk_ff2e5ca868c9e5af FOREIGN KEY (voyage_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offers ADD flash_sale_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE offers ADD flash_sale_discount NUMERIC(5, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE offers ALTER start_date TYPE DATE');
        $this->addSql('ALTER TABLE offers ALTER end_date TYPE DATE');
        $this->addSql('ALTER TABLE reclamations ADD response_deadline TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE refund_requests ADD reservation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE refund_requests ADD approved_amount NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE reservations ADD payment_reference VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE voyages ADD slug VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE voyages ALTER start_date TYPE DATE');
        $this->addSql('ALTER TABLE voyages ALTER end_date TYPE DATE');
        $this->addSql('CREATE UNIQUE INDEX uniq_30f7f9989d9b62 ON voyages (slug)');
    }
}
